version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: file_storage_db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: file_storage_api
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  adminer:
    image: adminer
    container_name: file_storage_adminer
    restart: always
    ports:
      - '8080:8080'

volumes:
  postgres_data: